services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${SA_PASSWORD}
      MSSQL_PID: "Developer"
    volumes:
      - sqlserver_data:/var/opt/mssql
    restart: unless-stopped

  customer-api:
    build:
      context: .
      dockerfile: Services/Customer/Customer.API/Dockerfile
    image: customer-api:dev   # tag local
    container_name: customer-api
    depends_on:
      - sqlserver
    ports:
      - "2323:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnectionString: ${DEFAULT_CONNECTION_STRING}
    restart: unless-stopped

volumes:
  sqlserver_data:
